In [1]:
import numpy as np

In [2]:
#Question1
def addition(arr1,arr2):
    try:
        return np.add(arr1,arr2)
    except Exception as e:
        print("Error occurred!\n",e)

In [11]:
#Question2
def multiplication(arr1,arr2):
    try:
        return np.matmul(arr1,arr2)
    except Exception as e:
         print("Error occurred!\n",e)

In [15]:
rows1=int(input("Enter number of rows in array 1 "))
cols1=int(input("Enter number of columns in array 1 "))
rows2=int(input("Enter number of rows in array 2 "))
cols2=int(input("Enter number of columns in array 2"))
arr1=np.empty((rows1,cols1),dtype=int)
arr2=np.empty((rows2,cols2),dtype=int)
print("Enter elements of array 1")
for i in range(rows1):
    for j in range(cols1):
        arr1[i][j]=int(input())
print("Enter elements of array 2")
for i in range(rows2):
    for j in range(cols2):
        arr2[i][j]=int(input())
print("Sum of two matrices :",addition(arr1,arr2))
print("Product of two matrices :",multiplication(arr1,arr2))

Enter number of rows in array 1 1
Enter number of columns in array 1 2
Enter number of rows in array 2 2
Enter number of columns in array 21
Enter elements of array 1
1
1
Enter elements of array 2
2
2
Sum of two matrices : [[3 3]
 [3 3]]
Product of two matrices : [[4]]


In [16]:
#Question3
def transpose(arr):
    try:
        return np.transpose(arr)
    except Exception as e:
         print("Error occurred!\n",e)

In [25]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix before tansposing is :",arr)
arr=transpose(arr)
print("Matrix after tansposing is :",arr)


Matrix before tansposing is : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix after tansposing is : [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [32]:
#Question4
def sortwords(lst):
    lst=[rec.lower() for rec in lst.split(" ")]
    for i in sorted(lst):
        yield i

In [33]:
for i in sortwords("I am sorting this string words in alphabetical order"):
    print(i)

alphabetical
am
i
in
order
sorting
string
this
words


In [60]:
#Question5
import re
def removePunctuation(str1):
    res=re.sub(r'[^\w\s]','',str1)
    return res

In [61]:
removePunctuation("Hello All!!Welcome to coding.This is the first code.")

'Hello AllWelcome to codingThis is the first code'